
# Windows extensions

code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.powershell
code --install-extension ritwickdey.LiveServer
code --install-extension thekalinga.bootstrap4-vscode
code --install-extension xabikos.JavaScriptSnippets

# Mac extenssions

code --install-extension alefragnani.project-manager
code --install-extension bibhasdn.git-easy
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension cweijan.vscode-office
code --install-extension docsmsft.docs-preview
code --install-extension donjayamanne.git-extension-pack
code --install-extension donjayamanne.githistory
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension GregorBiswanger.json2ts
code --install-extension kiteco.kite
code --install-extension loiane.ts-extension-pack
code --install-extension mhutchie.git-graph
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vscode-remote.remote-containers
code --install-extension pmneo.tsimporter
code --install-extension rbbit.typescript-hero
code --install-extension redhat.java
code --install-extension redhat.vscode-xml
code --install-extension stringham.move-ts
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension waderyan.gitblame
code --install-extension yuenm18.ooxml-viewer
code --install-extension ziyasal.vscode-open-in-github