name: py36
channels:
- soumith
- menpo
- conda-forge
- anaconda-fusion
- defaults
dependencies:
- python=3.6
- defaults::numpy
- defaults::numpydoc
- defaults::pandas
- defaults::pandas-datareader
- defaults::pandocfilters
- defaults::pandas-datareader
- defaults::pandocfilters
- defaults::scipy
- defaults::matplotlib
- defaults::scikit-learn
- defaults::scikit-image
- defaults::ipython
- defaults::ipykernel
- defaults::cython
- defaults::jupyter
- defaults::qt
- defaults::sympy
- defaults::nose
- defaults::seaborn
- defaults::bokeh
- defaults::Flask
- conda-forge::flask-restful
- defaults::sqlalchemy
- defaults::future
- menpo::dlib
- defaults::graphviz
- defaults::pydotplus
- defaults::beautifulsoup4
- defaults::glueviz
- defaults::more-itertools
- defaults::Quandl
- defaults::scrapy
- defaults::snakeviz
- defaults::sphinx
- defaults::ipyparallel
- defaults::requests
- defaults::progressbar2
- defaults::Basemap
- defaults::NetworkX
- defaults::virtualenv
- defaults::coverage
- defaults::flake8
- defaults::pyyaml
- pip:
    - cookiecutter
    - pip-review
    - pip-tools
    - PyMySQL
    - python-wordpress-xmlrpc
    - tox
    - tox-travis
    - twine
    - twython
    - versioneer
    - yahoo-finance
    - packaging
    - tqdm
    - nltk
    - statsmodels
    - tensorflow
    - theano
    - keras
    - lightgbm
    - dlib
    - ta-lib
    - IbPy2
    - pyfolio
    - markdown
    - hyperopt
    - kivy
    - prettytable
    - tox
    - watchdog
    - bumpversion
    - pandas_datareader
    - imbalanced-learn
    - category_encoders
    - pyfolio
