name: py36
channels:
- soumith
- conda-forge
- anaconda-fusion
- defaults
dependencies:
- python=3.6
- alabaster
- anyqt
- appnope
- appscript
- arrow
- asn1crypto
- astroid
- attrs
- automat
- babel
- backports
- beautifulsoup4
- binaryornot
- bitarray
- bkcharts
- blaze
- bleach
- bokeh
- boto
- boto3
- botocore
- certifi
- cffi
- chardet
- chest
- click
- cloudpickle
- clyent
- colorama
- configobj
- constantly
- contextlib2
- cryptography
- cssselect
- cycler
- cython
- cytoolz
- dask
- datashape
- decorator
- dill
- distributed
- django
- docutils
- entrypoints
- et_xmlfile
- fastcache
- filelock
- flake8
- flask
- flask-cors
- future
- get_terminal_size
- gevent
- glob2
- glue-core
- glue-vispy-viewers
- glueviz
- gmpy2
- graphviz
- greenlet
- heapdict
- html5lib
- hyperlink
- hypothesis
- idna
- imageio
- imagesize
- incremental
- inflection
- ipykernel
- ipyparallel
- ipython
- ipython_genutils
- ipywidgets
- isort
- itsdangerous
- jdcal
- jedi
- jinja2
- jinja2-time
- jmespath
- joblib
- jsonschema
- jupyter
- jupyter_client
- jupyter_console
- jupyter_core
- keyring
- keyrings.alt
- lazy-object-proxy
- llvmlite
- locket
- lxml
- mako
- markdown
- markupsafe
- matplotlib
- mccabe
- mistune
- mkl-service
- more-itertools
- mpmath
- msgpack-python
- multipledispatch
- navigator-updater
- nbconvert
- nbformat
- networkx
- nlopt
- nltk
- nose
- notebook
- numpy
- numpydoc
- odo
- olefile
- openpyxl
- orange3
- packaging
- pandas-datareader
- pandocfilters
- parsel
- partd
- path.py
- pathlib2
- patsy
- pexpect
- pickleshare
- pillow
- pkginfo
- plotly
- ply
- poyo
- prompt_toolkit
- psutil
- ptyprocess
- py
- pyasn1
- pyasn1-modules
- pycodestyle
- pycosat
- pycparser
- pycrypto
- pycurl
- pydispatcher
- pyflakes
- pygments
- pygpu
- pylint
- pympler
- pymysql
- pyodbc
- pyopenssl
- pyparsing
- pyqt
- pyqtgraph
- pysocks
- pytest
- python-dateutil
- python.app
- pytorch
- pytz
- pyyaml
- pyzmq
- qtawesome
- qtconsole
- qtpy
- quandl
- queuelib
- redis-py
- requests
- requests-file
- requests-ftp
- rope
- ruamel_yaml
- s3fs
- s3transfer
- scipy
- scrapy
- seaborn
- service_identity
- setuptools
- simplegeneric
- singledispatch
- sip
- six
- scikit-learn
- snakeviz
- snowballstemmer
- sockjs-tornado
- sortedcollections
- sortedcontainers
- sphinx
- sphinxcontrib
- sphinxcontrib-websupport
- spyder
- sqlalchemy
- statsmodels
- sympy
- tblib
- terminado
- testpath
- theano
- toolz
- torchvision
- tornado
- tqdm
- traitlets
- twisted
- typing
- unicodecsv
- urllib3
- virtualenv
- w3lib
- wcwidth
- webencodings
- werkzeug
- wheel
- whichcraft
- widgetsnbextension
- wrapt
- xlrd
- xlsxwriter
- xlwings
- xlwt
- zict
- zope
- zope.interface
- pip
- pip:
    - cookiecutter
    - coverage
    - cryptography
    - dill
    - dlib
    - face-recognition
    - face-recognition-models
    - fix-yahoo-finance
    - IbPy2
    - Keras
    - Kivy
    - Kivy-Garden
    - lightgbm
    - mxnet
    - packaging
    - pathtools
    - pep440
    - pip-review
    - pip-tools
    - PyMySQL
    - python-wordpress-xmlrpc
    - PyYAML
    - Quamash
    - requests-oauthlib
    - requests-toolbelt
    - ReText
    - simplejson
    - TA-Lib
    - tensorboard
    - tensorflow
    - tox
    - tox-travis
    - twine
    - twython
    - versioneer
    - yahoo-finance